# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a2a2c059a07d37f73acbadd78bb9535b03bac33a29f8b29aeffc36e4a8d9e2cbb89a06ecfc71280a210a1b6f7d19f3a092d6dc02a27fe17fdabde67feb1d8729

test:
  secret_key_base: 0deed02101de21c663a84f4ed45647a69daaa510523b01d4d7a60ece0f4f572ca7421d460928051a07a28e1a061bcd9c0697afa60c8c2d78224c3470a14dd889

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
